pipeline {
     agent any
     triggers {
          pollSCM('* * * * *')
     }
     stages {

       
          stage("print branch name") {
                echo "I am the ${env.BRANCH_NAME} branch"
            }
         
         
          stage("Code coverage") {

                    if (env.BRANCH_NAME == "main") {
                        steps {
                                sh '''
                                 pwd
                                 chmod + x sample1
                                 cd sample1
                                 pwd
                                 chmod + x gradlew
                                ./gradlew jacocoTestReport
                                '''
                                sh '''
                                 pwd
                                 chmod + x sample1
                                 cd sample1
                                 pwd
                                 chmod + x gradlew
                                ./gradlew jacocoTestCoverageVerification
                                '''
                        }
                    }
                    else{
                        echo "Code coverage skipped because of non main branch"
                    }
            }
        
        
            stage("Unit test") {
                  if (env.BRANCH_NAME != "main") {
                        steps {
                                sh '''
                                 pwd
                                 chmod + x sample1
                                 cd sample1
                                 pwd
                                 chmod + x gradlew
                                ./gradlew test
                                '''
                        }
                  }else{
                    echo "Unit test skipped because of main branch" 
                  }
            }
                    
            stage("Static code analysis") {
                 if (env.BRANCH_NAME != "main") {
                        steps {
                                sh '''
                                 pwd
                                 chmod + x sample1
                                 cd sample1
                                 pwd
                                 chmod + x gradlew
                                ./gradlew checkstyleMain
                                '''
                        }
                 }
                 else{
                    echo "Static code analysis skipped because of main branch" 
                  }
             }
       }
     
     
}
